# Generated by Django 3.2.9 on 2021-11-24 20:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PubKey',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpub1', models.CharField(max_length=130, unique=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_keys', to='wallets.key')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField()),
                ('name', models.TextField(unique=True)),
                ('addressType', models.TextField(max_length=9)),
                ('network', models.TextField(max_length=7, unique=True)),
                ('url', models.URLField(verbose_name='http://bitcoind.localhost:8080')),
                ('username', models.TextField(max_length=20, unique=True)),
                ('requiredSigners', models.TextField(verbose_name=1)),
                ('totalSigners', models.TextField(verbose_name=1)),
                ('keys', models.ManyToManyField(related_name='wallet', to='wallets.PubKey')),
            ],
        ),
    ]
