# Generated by Django 3.2.9 on 2021-12-05 20:16

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=False)),
                ('least_received', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16)),
                ('least_received_confirmed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16)),
                ('label', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('migrated_to_transactions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime.now)),
                ('executed_at', models.DateTimeField(default=None, null=True)),
                ('under_execution', models.BooleanField(default=False)),
                ('to_bitcoinaddress', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('txid', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='keys',
            field=models.ManyToManyField(related_name='pub_keys', to='wallets.PubKey'),
        ),
    ]
