# Generated by Django 3.2.13 on 2022-04-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20220422_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='user',
        ),
    ]
