# Generated by Django 3.2.13 on 2022-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_key_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
