# Generated by Django 3.2.13 on 2022-04-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_key_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ('-date',)},
        ),
    ]
