# Generated by Django 3.2.13 on 2022-04-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_alter_key_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={},
        ),
    ]
