# Generated by Django 3.2.13 on 2022-04-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_key_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='date',
        ),
        migrations.RemoveField(
            model_name='key',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='network',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='url',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='username',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
