# Generated by Django 3.2.13 on 2022-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_auto_20220424_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
