# Generated by Django 3.2.13 on 2022-04-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet'),
            preserve_default=False,
        ),
    ]
